### ISSUE TITLE
Upgrade to latest open release

### ISSUE THREAD

**Issue by cgillis-aras** [ArasLabs/lc-based-props-and-fields#1]
This needs to be tested against 11.0 SP9 and upgraded if necessary.

**Comment by EliJDonahue** [comment]
Retarget to current open release: 11.0 SP12.

**Comment by sampoearas** [comment]
Project needs to be archived and new version(s) released as the original author has an improved package that splits the methods into 2 separate packages

**Comment by sampoearas** [comment]
Replaced with [PAV](https://github.com/ArasLabs/property-advanced-validation) and [FFAR](https://github.com/ArasLabs/form-field-advanced-rendering)
